name: Deploy

on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed

jobs:
  deploy:
    if: ${{github.event.workflow_run.conclusion == "success" && github.ref === 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Install Railway CLI
        run: pnpm add --global @railway/cli
      - name: Deploy to Railway
        run: railway up "emoji-generator"
        env: ${{secrets.RAILWAY_TOKEN}}