name: Deploy

on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Install Railway CLI
        run: pnpm add --global @railway/cli
      - name: Verify Railway login
        run: railway whoami
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Deploy to Railway
        run: railway up --service="random-emoji" --yes
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}